# Generated by Django 5.0.6 on 2024-05-27 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_alter_filmresults_a_new_hope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmresults',
            name='bad_batch',
        ),
        migrations.RemoveField(
            model_name='filmresults',
            name='book_of_boba_fett',
        ),
        migrations.RemoveField(
            model_name='filmresults',
            name='clone_wars',
        ),
        migrations.RemoveField(
            model_name='filmresults',
            name='empire_strikes_back',
        ),
        migrations.RemoveField(
            model_name='filmresults',
            name='force_awakens',
        ),
        migrations.RemoveField(
            model_name='filmresults',
            name='last_jedi',
        ),
        migrations.RemoveField(
            model_name='filmresults',
            name='mandalorian',
        ),
        migrations.RemoveField(
            model_name='filmresults',
            name='phantom_menace',
        ),
        migrations.RemoveField(
            model_name='filmresults',
            name='rise_of_skywalker',
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_bad_batch',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_book_of_boba_fett',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_clone_wars',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_empire_strikes_back',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_force_awakens',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_last_jedi',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_mandalorian',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_phantom_menace',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmresults',
            name='the_rise_of_skywalker',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='a_new_hope',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='ahsoka',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='andor',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='attack_of_the_clones',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='obi_wan_kenobi',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='rebels',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='resistance',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='return_of_the_jedi',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='revenge_of_the_sith',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='rogue_one',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='solo',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='tales_of_the_empire',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='tales_of_the_jedi',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmresults',
            name='visions',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
