# List of film names in normalized format.
FILMS = [
    "a_new_hope",
    "empire_strikes_back",
    "return_of_the_jedi",
    "phantom_menace",
    "attack_of_the_clones",
    "revenge_of_the_sith",
    "force_awakens",
    "last_jedi",
    "rise_of_skywalker",
    "a_star_wars_story",
    "rogue_one",
    "solo",
    "mandalorian",
    "book_of_boba_fett",
    "obi_wan_kenobi",
    "andor",
    "ahsoka",
    "clone_wars",
    "rebels",
    "resistance",
    "bad_batch",
    "visions",
    "tales_of_the_empire",
    "tales_of_the_jedi",
]

# Tuples are critic and audience score, respectively, from Rotten Tomatoes
RT_CA = {
    "a_new_hope": (93, 96),
    "empire_strikes_back": (95, 97),
    "return_of_the_jedi": (83, 94),
    "phantom_menace": (53, 59),
    "attack_of_the_clones": (65, 56),
    "revenge_of_the_sith": (79, 66),
    "force_awakens": (93, 85),
    "last_jedi": (91, 41),
    "rise_of_skywalker": (51, 86),
    "a_star_wars_story": (69, 63),
    "rogue_one": (84, 86),
    "solo": (69, 63),
    "mandalorian": (90, 78),
    "book_of_boba_fett": (66, 53),
    "obi_wan_kenobi": (82, 62),
    "andor": (96, 86),
    "ahsoka": (86, 69),
    "clone_wars": (93, 91),
    "rebels": (98, 84),
    "resistance": (92, 47),
    "bad_batch": (88, 84),
    "visions": (98, 66),
    "tales_of_the_empire": (87, 50),
    "tales_of_the_jedi": (100, 93),
}
