# Generated by Django 5.0.6 on 2024-05-27 10:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('force_alignment', models.IntegerField(choices=[(0, 'Light Side'), (1, 'Force Neutral'), (2, 'Dark Side/Sith')], default=1)),
                ('gender', models.IntegerField(choices=[(0, 'Woman'), (1, 'Nonbinary'), (2, 'Genderfluid'), (3, 'Man'), (4, 'Prefer not to answer'), (5, 'Other')], default=4)),
                ('looking_for', models.IntegerField(choices=[(0, 'Women'), (1, 'Men and Women'), (2, 'Neither'), (3, 'All/Any'), (4, 'Men')], default=3)),
                ('profile_icon', models.CharField(choices=[('icon1', 'Icon 1'), ('icon2', 'Icon 2'), ('icon3', 'Icon 3'), ('icon4', 'Icon 4'), ('icon5', 'Icon 5'), ('icon6', 'Icon 6'), ('icon7', 'Icon 7'), ('icon8', 'Icon 8'), ('icon9', 'Icon 9'), ('icon10', 'Icon 10')], default='icon1', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=30)),
                ('instagram', models.CharField(blank=True, max_length=30)),
                ('twitter', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('matches', models.ManyToManyField(related_name='matched_by', to=settings.AUTH_USER_MODEL)),
                ('suggestions', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
