# Generated by Django 5.0.6 on 2024-05-25 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='force_alignment',
            field=models.IntegerField(choices=[(0, 'Light Side'), (1, 'Force Neutral'), (2, 'Dark Side/Sith')], default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Woman'), (1, 'Nonbinary'), (2, 'Genderfluid'), (3, 'Man'), (4, 'Prefer not to answer'), (5, 'Other')], default=4),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='looking_for',
            field=models.IntegerField(choices=[(0, 'Women'), (1, 'Men and Women'), (2, 'Neither'), (3, 'All/Any'), (4, 'Men')], default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='matches',
            field=models.ManyToManyField(related_name='matched_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_icon',
            field=models.CharField(choices=[('icon1', 'Icon 1'), ('icon2', 'Icon 2'), ('icon3', 'Icon 3'), ('icon4', 'Icon 4'), ('icon5', 'Icon 5'), ('icon6', 'Icon 6'), ('icon7', 'Icon 7'), ('icon8', 'Icon 8'), ('icon9', 'Icon 9'), ('icon10', 'Icon 10')], default='icon1', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suggestions',
            field=models.ManyToManyField(related_name='suggested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]