# Generated by Django 5.0.6 on 2024-05-25 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_customuser_bio_customuser_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='suggestions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
