# Generated by Django 5.0.6 on 2024-05-26 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_customuser_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_matches',
            field=models.ManyToManyField(blank=True, null=True, related_name='approved_matches_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='matches_matches',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
