# Generated by Django 5.0.6 on 2024-05-27 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_customuser_matches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='approved_matches',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='matches_matches',
        ),
        migrations.AddField(
            model_name='customuser',
            name='matches',
            field=models.ManyToManyField(related_name='matched_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suggestions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
