# Generated by Django 5.0.6 on 2024-05-27 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_customuser_approved_matches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchie', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
